### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jack-Rickwood** [Svirusx/NetHunter-s7-kernel-StockOreo#1]
@Svirusx 
So once this is finished, will it allow me to flash the kali nethunter kernel on my stock oreo samsung rom? If it does, thank you so much! Do you have any idea how long it will take to complete, and do you know wether badusb will work? Thanks again!

**Comment by Svirusx** [comment]
Yes, i'm making it from last samsung kernel source for herolte Oreo. After testing all i'm going to make version for hero2lte too and publicate it at xda forum. Like Nethunter for LineageOS 14.1.
I make only kernels and use stock boot.img so it need some patches to use after flash it like wifi fix etc... but i'm going to write all in xda topic when i test it.
Maybe later i make AiO kernel in one .zip but for now no time for it.

badusb works, hid attacks too.
