### ISSUE TITLE
Wireguard module not available?

### ISSUE THREAD

**Issue by eisengrau** [Svirusx/NetHunter-s7-kernel-StockOreo#2]
Hello,

I followed the instructions here https://forum.xda-developers.com/galaxy-s7/development/kernel-nethunter-lineageos-16-0-rom-t3921429 to patch this kernel, on my S7 wunning Lineage 16. All is fine, but it doesn't seem that it includes the wireguard module, as stated in your first post, under extra. When I launch the WG app it still states that it is using the "userspace go implelentation". Is there something that I missed?

Thanks,

**Comment by Svirusx** [comment]
Do you use root? This kernel is patched but Wireguard kernel module need to have root.
